name: VocabuLearn
description: Une application aidant à trouver et à apprendre des mots de vocabulaires en français/anglais.
publish_to: 'none'
version: 2.0.1+6

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  path_provider: ^2.0.8
  fuzzywuzzy: ^0.1.7
  settings_ui: ^2.0.2
  yaml: ^3.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0

flutter_icons:
# android: true
  ios: true
  image_path: "icon/original.png"
flutter:
  uses-material-design: true
  assets:
    - assets/VOCABULEARN_ICON.png
    - assets/DELETE.yaml